### ISSUE TITLE
Doesn't update.

### ISSUE THREAD

**Issue by MarijnStevens** [itamarwe/angular-chartist#4]
Chart doesn't redraw when values is changed.

**Comment by itamarwe** [comment]
Could you provide an example?
I think the issue is that we don't deep watch `data`.

**Comment by itamarwe** [comment]
I added the option to deep watch the `data` and the `options`  in https://github.com/itamarwe/angular-chartist/commit/f846da33512bbfb10af52ff5ef45467ad3b0d8d8

just add `deep-watch-data="true"` to the chartist element and it should update the chart whenever you change `data`.
