### ISSUE TITLE
Global space pollution and comparison style

### ISSUE THREAD

**Issue by colonelz** [itamarwe/angular-chartist#5]
Extend the variable definitions with deepwatch and type which now are visible and polluting global space. The deepwatch variable looks like an unused fragment and may be removed.

After change:
```javascript
var data, options, responsiveOptions, selector, updateChart, deepWatchData, deepWatchOptions, deepwatch, type;
```

Comparison should be equal by value and type.
 
After change:
```javascript
    if (type === 'line'){
```

**Comment by itamarwe** [comment]
Could you please create a pull request with the changes above for me to review and merge?
Thanks.

**Comment by itamarwe** [comment]
Thanks.
I fixed the issues above.
